package com.example.redditandroid.models

data class SubredditParent(
    val kind:String,
    val subreddit_data:Subreddit
)


data class Subreddit(
    val user_flair_background_color : String,
    val submit_text_html : String,
    val restrict_posting : Boolean,
    val user_is_banned : Boolean,
    val free_form_reports : Boolean,
    val wiki_enabled : Boolean,
    val user_is_muted : Boolean,
    val user_can_flair_in_sr : Boolean,
    val display_name : String,
    val header_img : String,
    val title : String,
    val allow_galleries : Boolean,
    val icon_size : List<Int>,
    val primary_color : String,
    val active_user_count : Int,
    val icon_img : String,
    val display_name_prefixed : String,
    val accounts_active : Int,
    val public_traffic : Boolean,
    val subscribers : Int,
    val user_flair_richtext : List<String>,
    val videostream_links_count : Int,
    val name : String,
    val quarantine : Boolean,
    val hide_ads : Boolean,
    val prediction_leaderboard_entry_type : String,
    val emojis_enabled : Boolean,
    val advertiser_category : String,
    val public_description : String,
    val comment_score_hide_mins : Int,
    val allow_predictions : Boolean,
    val user_has_favorited : Boolean,
    val user_flair_template_id : String,
    val community_icon : String,
    val banner_background_image : String,
    val original_content_tag_enabled : Boolean,
    val community_reviewed : Boolean,
    val submit_text : String,
    val description_html : String,
    val spoilers_enabled : Boolean,
    val header_title : String,
    val header_size : String,
    val user_flair_position : String,
    val all_original_content : Boolean,
    val has_menu_widget : Boolean,
    val is_enrolled_in_new_modmail : String,
    val key_color_color : String,
    val can_assign_user_flair : Boolean,
    val created : Int,
    val wls : Int,
    val show_media_preview : Boolean,
    val submission_type : String,
    val user_is_subscriber : Boolean,
    val disable_contributor_requests : Boolean,
    val allow_videogifs : Boolean,
    val user_flair_type : String,
    val allow_polls : Boolean,
    val collapse_deleted_comments : Boolean,
    val emojis_custom_size : String,
    val public_description_html : String,
    val allow_videos : Boolean,
    val is_crosspostable_subreddit : Boolean,
    val notification_level : String,
    val can_assign_link_flair : Boolean,
    val accounts_active_is_fuzzed : Boolean,
    val submit_text_label : String,
    val link_flair_position : String,
    val user_sr_flair_enabled : Boolean,
    val user_flair_enabled_in_sr : Boolean,
    val allow_discovery : Boolean,
    val user_sr_theme_enabled : Boolean,
    val link_flair_enabled : Boolean,
    val subreddit_type : String,
    val suggested_comment_sort : String,
    val banner_img : String,
    val user_flair_text : String,
    val banner_background_color : String,
    val show_media : Boolean,
    val id : String,
    val user_is_moderator : Boolean,
    val over18 : Boolean,
    val description : String,
    val submit_link_label : String,
    val user_flair_text_color : String,
    val restrict_commenting : Boolean,
    val user_flair_css_class : String,
    val allow_images : Boolean,
    val lang : String,
    val whitelist_status : String,
    val url : String,
    val created_utc : Int,
    val banner_size : String,
    val mobile_banner_image : String,
    val user_is_contributor : Boolean,
    val allow_predictions_tournament : Boolean
)